- .github/workflows/docker.yml
- docker/docker-compose.yml
`ghcr.io/nimtable/nimtable:nightly`
https://github.com/nimtable/nimtable/pkgs/container/nimtable
> feat(ci): publish docker image to ghcr

- src/components/app-sidebar.tsx
Use subsequence match algorithm.
> feat: implement table search feature

- backend/src/main/java/io/nimtable/DistributionServlet.java
- src/app/table/info.tsx
- src/components/table/file-distribution-loading.tsx
- src/components/table/file-statistics.tsx
- src/components/table/optimize-sheet.tsx
- src/lib/data-loader.ts
> feat: optimize & move data distribution to table detail

- backend/src/main/java/io/nimtable/ManifestServlet.java
- src/app/table/snapshots.tsx
https://github.com/nimtable/nimtable/issues/69
> feat: snapshot & manifest display

- src/app/sql-editor/page.tsx
- src/app/table/snapshots.tsx
https://github.com/nimtable/nimtable/issues/73
> feat: support timetravel for snapshot

- backend/src/main/java/io/nimtable/DistributionServlet.java
- package-lock.json
- package.json
- src/app/table/snapshots.tsx
- src/components/table/snapshot-trend.tsx
- src/lib/data-loader.ts
> feat: support snapshot data size trend

- src/app/namespace/page.tsx
- src/lib/data-loader.ts
> feat: show Unknown instead of 0 in Total Data Size

- src/app/table/info.tsx
> feat: refine layout & add show partition info

- src/components/sidebar/tree-items.tsx
- Resolve https://github.com/nimtable/nimtable/issues/96
> fix: close namespaces by default

- docker/docker-compose.yml
Signed-off-by: xxchan <xxchan22f@gmail.com>
> fix(docker): add depends_on

- backend/src/main/java/io/nimtable/OptimizeServlet.java
- src/components/table/optimize-sheet.tsx
- src/lib/data-loader.ts
Resolve https://github.com/nimtable/nimtable/issues/100
Expose the following parameters for comapction:
- target-file-size-bytes
- strategy
- sort_order
- where
> feat: expose more parameters for compaction

- backend/src/main/java/io/nimtable/DistributionServlet.java
- backend/src/main/java/io/nimtable/cache/DataDistributionCache.java
- backend/src/main/java/io/nimtable/db/entity/DataDistribution.java
- backend/src/main/java/io/nimtable/db/repository/DataDistributionRepository.java
- backend/src/main/resources/db/migration/postgresql/V1__init_schema.sql
- backend/src/main/resources/db/migration/sqlite/V1__init_schema.sql
Added caching for table distribution statistics to improve performance when retrieving file distribution data.
> support cache for data distribution

- backend/gradle.properties
- backend/src/main/java/io/nimtable/OptimizeServlet.java
- src/components/table/optimize-sheet.tsx
- src/components/ui/alert.tsx
- src/lib/data-loader.ts
> feat: show resource for compaction

- eslint.config.mjs
- package-lock.json
- package.json
- src/components/table/optimize-sheet.tsx
- src/components/table/snapshot-trend.tsx
Can't get eslint run locally previously.
Signed-off-by: xxchan <xxchan22f@gmail.com>
> chore: bump eslint

- src/app/table/snapshots.tsx
- src/components/table/file-distribution.tsx
- src/components/table/optimize-sheet.tsx
- src/components/table/snapshot-trend.tsx
- show compactoin history
- show compaction event in the snapshot trend
> feat: support compaction history and show compaction tag to the snapshot trends

- backend/src/main/java/io/nimtable/DistributionServlet.java
- backend/src/main/java/io/nimtable/cache/DataDistributionCache.java
- Avoid unnecessary table loading for data distribution cache
> fix: fix distribution cache to avoid unnecessary table loading

- src/app/table/info.tsx
- src/components/table/file-distribution.tsx
- src/components/table/optimize-sheet.tsx
> decide whether to compact a table

- .github/workflows/build.yml
- src/app/layout.tsx
- src/app/namespace/page.tsx
- src/app/sql-editor/page.tsx
- src/app/table/info.tsx
- src/app/table/snapshots.tsx
- src/components/app-sidebar.tsx
- src/components/shared/sql-editor-navbar.tsx
- src/components/shared/top-navbar.tsx
- src/components/ui/sidebar.tsx
Signed-off-by: xxchan <xxchan22f@gmail.com>
> refactor: move TooltipProvider to top-level

- package-lock.json
- package.json
- src/app/table/info.tsx
- src/components/table/actions.ts
- src/lib/agent/prompt.ts
TODO:
https://github.com/user-attachments/assets/155a3719-0e9b-4b8a-8a28-ee17a6dfed34
> feat: add basic table summary

- src/app/dashboard/ActivityFeed.tsx
- src/app/dashboard/TableWatchlist.tsx
> fix: show full name for dashboard table and show only compaction snapshot

- src/app/api/agent/table_summary/route.ts
- src/app/table/info.tsx
- src/components/table/actions.ts
- src/db/db.ts
- src/db/table-summary.ts
> feat: support user edit table summary

- src/app/users/layout.tsx
- src/app/users/page.tsx
- src/components/sidebar.tsx
- src/components/users/user-management.tsx
> feat: add Users and Signout

- backend/src/main/java/io/nimtable/UserServlet.java
- backend/src/main/java/io/nimtable/db/entity/Role.java
- backend/src/main/java/io/nimtable/db/entity/User.java
- backend/src/main/resources/db/migration/postgresql/V1__init_schema.sql
- src/components/users/add-user-dialog.tsx
- src/components/users/type.ts
- src/components/users/user-management.tsx
- src/components/users/user-table.tsx
- src/lib/api.yaml
- src/lib/client/types.gen.ts
> feat: Add role in user management

- src/components/memoized-markdown.tsx
Signed-off-by: xxchan <xxchan22f@gmail.com>
> feat: improve AI chat text color

- backend/src/main/resources/db/migration/postgresql/V1__init_schema.sql
- prisma/migrations/20240321000000_recreate_user_profiles/migration.sql
- prisma/schema.prisma
- src/app/acc-api/auth/login/route.ts
- src/app/acc-api/auth/reset-password/route.ts
- src/app/acc-api/user-info/route.ts
- src/app/settings/account/page.tsx
- src/components/sidebar.tsx
- src/components/users/user-management.tsx
- src/components/users/user-table.tsx
- src/contexts/auth-context.tsx
- src/lib/acc-api/api.yaml
- src/lib/acc-api/client/types.gen.ts
> feat: add user profile

- src/app/data/namespaces/NamespacesContent.tsx
- src/app/namespace/page.tsx
- src/components/namespace/CreateNamespaceModal.tsx
- src/lib/data-loader.ts
> feat: support creating namespaces
